const data={
  Family:[
    {
      word:'Mother',
      translate:'Мама',
      image:'../src/img/family/mother.jpg',
      audio:'../src/audio/family/mother.mp3',
    },{
      word:'Father',
      translate:'Папа',
      image:'../src/img/family/father.jpg',
      audio:'../src/audio/family/father.mp3',
    },{
      word:'Brother',
      translate:'Брат',
      image:'../src/img/family/brother.jpg',
      audio:'../src/audio/family/brother.mp3',
    },{
      word:'Sister',
      translate:'Сестра',
      image:'../src/img/family/sister.jpg',
      audio:'../src/audio/family/sister.mp3',
    },{
      word:'Son',
      translate:'Сын',
      image:'../src/img/family/son.jpg',
      audio:'../src/audio/family/son.mp3',
    },{
      word:'Daughter',
      translate:'Дочь',
      image:'../src/img/family/daughter.jpg',
      audio:'../src/audio/family/daughter.mp3',
    },{
      word:'Grandmother',
      translate:'Бабушка',
      image:'../src/img/family/grandmother.jpg',
      audio:'../src/audio/family/grandmother.mp3',
    },{
      word:'Grandfather',
      translate:'Дедушка',
      image:'../src/img/family/grandfather.jpg',
      audio:'../src/audio/family/grandfather.mp3',
    },
  ],
  Clothes:[
    {
      word:'Socks',
      translate:'Носки',
      image:'../src/img/clothes/socks.jpg',
      audio:'../src/audio/clothes/socks.mp3',
    },{
      word:'Jeans',
      translate:'Джинсы',
      image:'../src/img/clothes/jeans.jpg',
      audio:'../src/audio/clothes/jeans.mp3',
    },{
      word:'Shirt',
      translate:'Рубашка',
      image:'../src/img/clothes/shirt.jpg',
      audio:'../src/audio/clothes/shirt.mp3',
    },{
      word:'Dress',
      translate:'Платье',
      image:'../src/img/clothes/dress.jpg',
      audio:'../src/audio/clothes/dress.mp3',
    },{
      word:'Skirt',
      translate:'Юбка',
      image:'../src/img/clothes/skirt.jpg',
      audio:'../src/audio/clothes/skirt.mp3',
    },{
      word:'Cap',
      translate:'Шапка',
      image:'../src/img/clothes/cap.jpg',
      audio:'../src/audio/clothes/cap.mp3',
    },{
      word:'Sweater',
      translate:'Свитер',
      image:'../src/img/clothes/sweater.jpg',
      audio:'../src/audio/clothes/sweater.mp3',
    },{
      word:'Boots',
      translate:'Ботинки',
      image:'../src/img/clothes/boots.jpg',
      audio:'../src/audio/clothes/boots.mp3',
    },
  ],Animal:[
    {
      word:'Cat',
      translate:'Кошка',
      image:'../src/img/animals/cat.jpg',
      audio:'../src/audio/animal/cat.mp3',
    },{
      word:'Turtle',
      translate:'Черепаха',
      image:'../src/img/animals/turtle.jpg',
      audio:'../src/audio/animal/turtle.mp3',
    },{
      word:'Horse',
      translate:'Лошадь',
      image:'../src/img/animals/horse.jpg',
      audio:'../src/audio/animal/horse.mp3',
    },{
      word:'Rabbit',
      translate:'Кролик',
      image:'../src/img/animals/rabbit.jpg',
      audio:'../src/audio/animal/rabbit.mp3',
    },{
      word:'Lion',
      translate:'Лев',
      image:'../src/img/animals/lion.jpg',
      audio:'../src/audio/animal/lion.mp3',
    },{
      word:'Bird',
      translate:'Птица',
      image:'../src/img/animals/bird.jpg',
      audio:'../src/audio/animal/bird.mp3',
    },{
      word:'Giraffe',
      translate:'Жираф',
      image:'../src/img/animals/giraffe.jpg',
      audio:'../src/audio/animal/giraffe.mp3',
    },{
      word:'Dog',
      translate:'Собака',
      image:'../src/img/animals/dog.jpg',
      audio:'../src/audio/animal/dog.mp3',
    },
  ],Food:[
    {
      word:'Bread',
      translate:'Хлеб',
      image:'../src/img/food/bread.jpg',
      audio:'../src/audio/food/bread.mp3',
    },{
      word:'Egg',
      translate:'Яйца',
      image:'../src/img/food/eggs.jpg',
      audio:'../src/audio/food/eggs.mp3',
    },{
      word:'Cherry',
      translate:'Вишня',
      image:'../src/img/food/cherry.jpg',
      audio:'../src/audio/food/cherry.mp3',
    },{
      word:'Cheese',
      translate:'Сыр',
      image:'../src/img/food/cheese.jpg',
      audio:'../src/audio/food/cheese.mp3',
    },{
      word:'Tomato',
      translate:'Помидор',
      image:'../src/img/food/tomato.jpg',
      audio:'../src/audio/food/tomato.mp3',
    },{
      word:'Pizza',
      translate:'Пицца',
      image:'../src/img/food/pizza.jpg',
      audio:'../src/audio/food/pizza.mp3',
    },{
      word:'Soup',
      translate:'Cуп',
      image:'../src/img/food/soup.jpg',
      audio:'../src/audio/food/soup.mp3',
    },{
      word:'Sandwich',
      translate:'Ботинки',
      image:'../src/img/food/sandwich.jpg',
      audio:'../src/audio/food/sandwich.mp3',
    },
  ],Figures:[
    {
      word:'Circle',
      translate:'Круг',
      image:'../src/img/figure/circle.jpg',
      audio:'../src/audio/figure/circle.mp3',
    },{
      word:'Rectangle',
      translate:'Прямоугольник',
      image:'../src/img/figure/rectangle.jpg',
      audio:'../src/audio/figure/rectangle.mp3',
    },{
      word:'Triangle',
      translate:'Треугольник',
      image:'../src/img/figure/triangle.jpg',
      audio:'../src/audio/figure/triangle.mp3',
    },{
      word:'Square',
      translate:'Квадрат',
      image:'../src/img/figure/square.jpg',
      audio:'../src/audio/figure/square.mp3',
    },{
      word:'Ellipse',
      translate:'Эллипс',
      image:'../src/img/figure/ellipse.jpg',
      audio:'../src/audio/figure/ellipse.mp3',
    },{
      word:'Star',
      translate:'Звезда',
      image:'../src/img/figure/star.jpg',
      audio:'../src/audio/figure/star.mp3',
    },{
      word:'Diamond',
      translate:'Ромб',
      image:'../src/img/figure/diamond.jpg',
      audio:'../src/audio/figure/diamond.mp3',
    },{
      word:'Heart',
      translate:'Сердце',
      image:'../src/img/figure/heart.jpg',
      audio:'../src/audio/figure/heart.mp3',
    },
  ],Nature:[
    {
      word:'Tree',
      translate:'Дерево',
      image:'../src/img/nature/tree.jpg',
      audio:'../src/audio/nature/tree.mp3',
    },{
      word:'Flower',
      translate:'Цветок',
      image:'../src/img/nature/flower.jpg',
      audio:'../src/audio/nature/flower.mp3',
    },{
      word:'Sea',
      translate:'Море',
      image:'../src/img/nature/sea.jpg',
      audio:'../src/audio/nature/sea.mp3',
    },{
      word:'Mountain',
      translate:'Гора',
      image:'../src/img/nature/mountain.jpg',
      audio:'../src/audio/nature/mountain.mp3',
    },{
      word:'Leaf',
      translate:'Лист',
      image:'../src/img/nature/leaf.jpg',
      audio:'../src/audio/nature/leaf.mp3',
    },{
      word:'Flame',
      translate:'Пламя',
      image:'../src/img/nature/flame.jpg',
      audio:'../src/audio/nature/flame.mp3',
    },{
      word:'Grass',
      translate:'Трава',
      image:'../src/img/nature/grass.jpg',
      audio:'../src/audio/nature/grass.mp3',
    },{
      word:'Sky',
      translate:'Небо',
      image:'../src/img/nature/sky.jpg',
      audio:'../src/audio/nature/sky.mp3',
    },
  ],Emotion:[
    {
      word:'Happy',
      translate:'Счастливый',
      image:'../src/img/emotion/happy.jpg',
      audio:'../src/audio/emotion/happy.mp3',
    },{
      word:'Angry',
      translate:'Сердитый',
      image:'../src/img/emotion/angry.jpg',
      audio:'../src/audio/emotion/angry.mp3',
    },{
      word:'Surprised',
      translate:'Удивленный',
      image:'../src/img/emotion/surprised.jpg',
      audio:'../src/audio/emotion/surprised.mp3',
    },{
      word:'Sad',
      translate:'Грустный',
      image:'../src/img/emotion/sad.jpg',
      audio:'../src/audio/emotion/sad.mp3',
    },{
      word:'Smile',
      translate:'Улыбка',
      image:'../src/img/emotion/smile.jpg',
      audio:'../src/audio/emotion/smile.mp3',
    },{
      word:'Scared',
      translate:'Испуганный',
      image:'../src/img/emotion/scared.jpg',
      audio:'../src/audio/emotion/scared.mp3',
    },{
      word:'Laugh',
      translate:'Смех',
      image:'../src/img/emotion/laugh.jpg',
      audio:'../src/audio/emotion/laugh.mp3',
    },{
      word:'Tired',
      translate:'Уставший',
      image:'../src/img/emotion/tired.jpg',
      audio:'../src/audio/emotion/tired.mp3',
    },
  ],Action:[
    {
      word:'Cook',
      translate:'Готовить',
      image:'../src/img/action/cook.jpg',
      audio:'../src/audio/action/cook.mp3',
    },{
      word:'Dance',
      translate:'Танцевать',
      image:'../src/img/action/dance.jpg',
      audio:'../src/audio/action/dance.mp3',
    },{
      word:'Draw',
      translate:'Рисовать',
      image:'../src/img/action/draw.jpg',
      audio:'../src/audio/action/draw.mp3',
    },{
      word:'Sing',
      translate:'Петь',
      image:'../src/img/action/sing.jpg',
      audio:'../src/audio/action/sing.mp3',
    },{
      word:'Read',
      translate:'Чиать',
      image:'../src/img/action/read.jpg',
      audio:'../src/audio/action/read.mp3',
    },{
      word:'Run',
      translate:'Бегать',
      image:'../src/img/action/run.jpg',
      audio:'../src/audio/action/run.mp3',
    },{
      word:'Jump',
      translate:'Прыгать',
      image:'../src/img/action/jump.jpg',
      audio:'../src/audio/action/jump.mp3',
    },{
      word:'Swim',
      translate:'Ботинки',
      image:'../src/img/action/swim.jpg',
      audio:'../src/audio/action/swim.mp3',
    },
  ],Categories:[
    {
      word:'Family',
      image:'../src/img/categories/Family.jpg',
    },{
      word:'Clothes',
      image:'../src/img/categories/clothes.jpg',
    },{
      word:'Animal',
      image:'../src/img/categories/animal.jpg',
    },{
      word:'Food',
      image:'../src/img/categories/food.jpg',
    },{
      word:'Figures',
      image:'../src/img/categories/figure.jpg',
    },{
      word:'Nature',
      image:'../src/img/categories/nature.jpg',
    },{
      word:'Emotion',
      image:'../src/img/categories/emotion.jpg',
    },{
      word:'Action',
      image:'../src/img/categories/Action.jpg',
    },
  ]
}
export default data;
